name: Cconomy_Database
version: '${project.version}'
main: fr.fuzeblocks.cconomy_database.CconomyDatabase
api-version: '1.16'
load: STARTUP
authors: [fuzeblocks]
commands:
  money:
    description: A money command
