name: Cconomy_Database
version: '${project.version}'
main: fr.fuzeblocks.cconomy_database.CconomyDatabase
api-version: '1.18'
load: STARTUP
authors: [fuzeblocks]
depend:
  - PlaceholderAPI
commands:
  money:
    description: A money command
